spring.application.name=SWEN2-Tour-Planner

# Fallbacks für env variables im Local Development (ohne Docker) mit :

# DataSource
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tour-planner}
spring.datasource.username=${DB_USER:user}
spring.datasource.password=${DB_PASSWORD:pass}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:create-drop}
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Hibernate Search
spring.jpa.properties.hibernate.search.backend.type=lucene
spring.jpa.properties.hibernate.search.backend.directory.type=local-filesystem
spring.jpa.properties.hibernate.search.backend.directory.root=data/index

# File upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
app.upload.dir=${UPLOAD_DIR:uploads/images}

# Data initialization
spring.sql.init.mode=always
# zuerst tables erstellen und dann data.sql importieren
spring.jpa.defer-datasource-initialization=true
