spring.application.name=SWEN2-Tour-Planner

# Fallbacks für env variables im Local Development (ohne Docker) mit :

# DataSource
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tour-planner}
spring.datasource.username=${DB_USER:user}
spring.datasource.password=${DB_PASSWORD:pass}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:create-drop}
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Data initialization
spring.sql.init.mode=always
# zuerst tables erstellen und dann data.sql importieren
spring.jpa.defer-datasource-initialization=true
