spring.application.name=SWEN2-Tour-Planner

# Fallbacks für env variables im Local Development (ohne Docker) mit :

# DataSource
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tour-planner}
spring.datasource.username=${DB_USER:tour-planner}
spring.datasource.password=${DB_PASSWORD:tour-planner}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
